# Generated by Django 4.2.3 on 2023-09-01 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(default='No question')),
                ('audio_input', models.TextField(default='No input')),
                ('prediction', models.TextField(default='No prediction')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2023, 9, 1, 10, 21, 29, 911592))),
            ],
        ),
    ]
