# Generated by Django 4.2.6 on 2023-10-22 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0002_alter_sentimentdata_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimentdata',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 22, 18, 53, 58, 466754)),
        ),
    ]
